### ISSUE TITLE
Files in the root of the source folder have invalid output

### ISSUE THREAD

**Issue by lee-chase** [lee-chase/gulp-index#1]
With the project structure

/src/filename.html

using the settings

gulp.task('html:index', () => {
  return gulp.src('./app/*.html')
    .pipe(plugins.index({relativePath: './app'}))
    .pipe(gulp.dest('.tmp'));
});

The index file contains

href="filename.html/"

it should be

href="filename.html"

**Comment by lee-chase** [comment]
This is due to the way path and file are extracted from the list of files. It produces the following parameters for the item-template:

filepath: 'filename.html',
filename: ''

 'item-template': (filepath, filename) => `<li class="index__item"><a class="index__item-link" href="${filepath}/${filename}">${filepath} - ${filename}</a></li>

This could be corrected by adjusting the template given the above information, however it should be fixed.

**Comment by dlemstra** [comment]
@lee-chase Would it be possible to publish a new release `0.0.9` that includes this fix?

**Comment by lee-chase** [comment]
@dlemstra done, although I'd already upped version to v0.1.0

**Comment by dlemstra** [comment]
Thanks for the quick reply and publication 👍
